spring.application.name=vehicleTracker

#mongodb properties
spring.data.mongodb.uri= mongodb://localhost:27017,localhost:27018,localhost:27019/
spring.data.mongodb.database=vehicle_tracker

jwt.secret-key=f462b03c4d1016d0af752f461be01480ab78d87a452f92374d25f2269dbca8e2
app.jwttoken.message=JWT Token generated successfully
# 24h in millisecond
security.jwt.expiration-time=86400000